apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  labels:
    name: prometheus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi