apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  storageClassName: slow
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.220
    path: "/VOLUMES/postgresql"
    readOnly: false