apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi