apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  storageClassName: valentinad
  capacity:
    storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.220
    path: /VOLUMES
    readOnly: false