apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  labels:
    name: prometheus
spec:
  storageClassName: openebs-device
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi