apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: grafana
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  #persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /VOLUMES/grafana
    server: 192.168.1.220
    readOnly: false