apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv10girwo1
  namespace: grafana
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  #mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs:
    server: 192.168.1.220
    path: "/VOLUMES"
    readOnly: false