apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2girwo1
  namespace: prometheus
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.220
    path: /VOLUMES
    readOnly: false